name: e2e

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [12.17.x, lts/*]

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
            
      - name: Install and Test
        run: |
          mkdir test && cd test

          npm init --yes
          npm add cpu-perf-counters
          
          node -e "const { begin, CounterType } = require('cpu-perf-counters'); const sampler = begin();"
