name: CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  setup:
    steps:
      - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo "$GITHUB_CONTEXT"
       
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.17.x, 16.x]
        # test unsupported platforms to check something reasonable happens
        include:
          - os: windows-latest
            node-version: 16.x
          - os: macos-latest
            node-version: 16.x

    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Set up Clang
        if: matrix.os == 'ubuntu-latest'
        uses: egor-tensin/setup-clang@v1
        with:
          version: 10
          platform: x64
      
      - name: Install CMake, Ninja
        uses: lukka/get-cmake@latest
      
      - name: Build
        run: npm install
        env:
          npm_config_build_from_source: true

      - run: npm test
 
