name: Linux prebuild & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Match tag to package version
        uses: geritol/match-tag-to-package-version@0.2.0
        with:
          TAG_PREFIX: v

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.17.x
          cache: 'npm'
      
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 10
          platform: x64
      
      - name: Install CMake, Ninja
        uses: lukka/get-cmake@latest
      
      - name: NPM install, test
        run: |
          npm install
          npm test
        env:
          npm_config_build_from_source: true

      - name: Upload prebuilt binaries
        run: npm run prebuild -- -u "$GH_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}

      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
